version: '3.8'

services:
  drupal:
    image: drupal:latest
    ports:
      - "81:80"
    volumes:
      - drupal_data:/var/www/html
  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  drupal_data:
  mysql_data:
